// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// calcF
NumericMatrix calcF(NumericVector lambda10, NumericVector lambda01, NumericMatrix lambda11);
RcppExport SEXP _mhazard_calcF(SEXP lambda10SEXP, SEXP lambda01SEXP, SEXP lambda11SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lambda10(lambda10SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda01(lambda01SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type lambda11(lambda11SEXP);
    rcpp_result_gen = Rcpp::wrap(calcF(lambda10, lambda01, lambda11));
    return rcpp_result_gen;
END_RCPP
}
// calc_lambda11
NumericMatrix calc_lambda11(NumericVector T1, NumericVector T2, NumericVector Y1, NumericVector Y2, NumericMatrix X, NumericMatrix dij11, NumericVector beta11);
RcppExport SEXP _mhazard_calc_lambda11(SEXP T1SEXP, SEXP T2SEXP, SEXP Y1SEXP, SEXP Y2SEXP, SEXP XSEXP, SEXP dij11SEXP, SEXP beta11SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type T1(T1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T2(T2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y1(Y1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y2(Y2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dij11(dij11SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta11(beta11SEXP);
    rcpp_result_gen = Rcpp::wrap(calc_lambda11(T1, T2, Y1, Y2, X, dij11, beta11));
    return rcpp_result_gen;
END_RCPP
}
// calcEE11
NumericVector calcEE11(NumericVector beta11, NumericVector Y1, NumericVector Y2, NumericVector T1, NumericVector T2, NumericVector Delta1, NumericVector Delta2, NumericMatrix X, NumericMatrix dij11);
RcppExport SEXP _mhazard_calcEE11(SEXP beta11SEXP, SEXP Y1SEXP, SEXP Y2SEXP, SEXP T1SEXP, SEXP T2SEXP, SEXP Delta1SEXP, SEXP Delta2SEXP, SEXP XSEXP, SEXP dij11SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type beta11(beta11SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y1(Y1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y2(Y2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T1(T1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T2(T2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Delta1(Delta1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Delta2(Delta2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dij11(dij11SEXP);
    rcpp_result_gen = Rcpp::wrap(calcEE11(beta11, Y1, Y2, T1, T2, Delta1, Delta2, X, dij11));
    return rcpp_result_gen;
END_RCPP
}
// calc_drij
arma::cube calc_drij(NumericVector Y1, NumericVector Y2, NumericVector T1, NumericVector T2, NumericVector Delta1, NumericVector Delta2);
RcppExport SEXP _mhazard_calc_drij(SEXP Y1SEXP, SEXP Y2SEXP, SEXP T1SEXP, SEXP T2SEXP, SEXP Delta1SEXP, SEXP Delta2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Y1(Y1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y2(Y2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T1(T1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T2(T2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Delta1(Delta1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Delta2(Delta2SEXP);
    rcpp_result_gen = Rcpp::wrap(calc_drij(Y1, Y2, T1, T2, Delta1, Delta2));
    return rcpp_result_gen;
END_RCPP
}
// margHaz
NumericVector margHaz(NumericVector Y, NumericVector T, NumericVector Delta);
RcppExport SEXP _mhazard_margHaz(SEXP YSEXP, SEXP TSEXP, SEXP DeltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Delta(DeltaSEXP);
    rcpp_result_gen = Rcpp::wrap(margHaz(Y, T, Delta));
    return rcpp_result_gen;
END_RCPP
}
// jointHazLambda
arma::cube jointHazLambda(NumericVector Y1, NumericVector Y2, NumericVector T1, NumericVector T2, NumericVector Delta1, NumericVector Delta2, int method);
RcppExport SEXP _mhazard_jointHazLambda(SEXP Y1SEXP, SEXP Y2SEXP, SEXP T1SEXP, SEXP T2SEXP, SEXP Delta1SEXP, SEXP Delta2SEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Y1(Y1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y2(Y2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T1(T1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T2(T2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Delta1(Delta1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Delta2(Delta2SEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(jointHazLambda(Y1, Y2, T1, T2, Delta1, Delta2, method));
    return rcpp_result_gen;
END_RCPP
}
// calcTemp2
arma::cube calcTemp2(NumericMatrix Fhat, NumericMatrix Lambda10, NumericMatrix Lambda01, NumericMatrix Lambda11);
RcppExport SEXP _mhazard_calcTemp2(SEXP FhatSEXP, SEXP Lambda10SEXP, SEXP Lambda01SEXP, SEXP Lambda11SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Fhat(FhatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Lambda10(Lambda10SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Lambda01(Lambda01SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Lambda11(Lambda11SEXP);
    rcpp_result_gen = Rcpp::wrap(calcTemp2(Fhat, Lambda10, Lambda01, Lambda11));
    return rcpp_result_gen;
END_RCPP
}
// jointHaz
NumericMatrix jointHaz(NumericVector Y1, NumericVector Y2, NumericVector T1, NumericVector T2, NumericVector Delta1, NumericVector Delta2);
RcppExport SEXP _mhazard_jointHaz(SEXP Y1SEXP, SEXP Y2SEXP, SEXP T1SEXP, SEXP T2SEXP, SEXP Delta1SEXP, SEXP Delta2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Y1(Y1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y2(Y2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T1(T1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T2(T2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Delta1(Delta1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Delta2(Delta2SEXP);
    rcpp_result_gen = Rcpp::wrap(jointHaz(Y1, Y2, T1, T2, Delta1, Delta2));
    return rcpp_result_gen;
END_RCPP
}
// triHaz
arma::cube triHaz(NumericVector Y1, NumericVector Y2, NumericVector Y3, NumericVector T1, NumericVector T2, NumericVector T3, NumericVector Delta1, NumericVector Delta2, NumericVector Delta3);
RcppExport SEXP _mhazard_triHaz(SEXP Y1SEXP, SEXP Y2SEXP, SEXP Y3SEXP, SEXP T1SEXP, SEXP T2SEXP, SEXP T3SEXP, SEXP Delta1SEXP, SEXP Delta2SEXP, SEXP Delta3SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Y1(Y1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y2(Y2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y3(Y3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T1(T1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T2(T2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T3(T3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Delta1(Delta1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Delta2(Delta2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Delta3(Delta3SEXP);
    rcpp_result_gen = Rcpp::wrap(triHaz(Y1, Y2, Y3, T1, T2, T3, Delta1, Delta2, Delta3));
    return rcpp_result_gen;
END_RCPP
}
// calcTemp3
arma::cube calcTemp3(arma::cube Fhat);
RcppExport SEXP _mhazard_calcTemp3(SEXP FhatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type Fhat(FhatSEXP);
    rcpp_result_gen = Rcpp::wrap(calcTemp3(Fhat));
    return rcpp_result_gen;
END_RCPP
}
// getBootCI
NumericMatrix getBootCI(NumericMatrix T);
RcppExport SEXP _mhazard_getBootCI(SEXP TSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type T(TSEXP);
    rcpp_result_gen = Rcpp::wrap(getBootCI(T));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mhazard_calcF", (DL_FUNC) &_mhazard_calcF, 3},
    {"_mhazard_calc_lambda11", (DL_FUNC) &_mhazard_calc_lambda11, 7},
    {"_mhazard_calcEE11", (DL_FUNC) &_mhazard_calcEE11, 9},
    {"_mhazard_calc_drij", (DL_FUNC) &_mhazard_calc_drij, 6},
    {"_mhazard_margHaz", (DL_FUNC) &_mhazard_margHaz, 3},
    {"_mhazard_jointHazLambda", (DL_FUNC) &_mhazard_jointHazLambda, 7},
    {"_mhazard_calcTemp2", (DL_FUNC) &_mhazard_calcTemp2, 4},
    {"_mhazard_jointHaz", (DL_FUNC) &_mhazard_jointHaz, 6},
    {"_mhazard_triHaz", (DL_FUNC) &_mhazard_triHaz, 9},
    {"_mhazard_calcTemp3", (DL_FUNC) &_mhazard_calcTemp3, 1},
    {"_mhazard_getBootCI", (DL_FUNC) &_mhazard_getBootCI, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_mhazard(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
