# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcF <- function(lambda10, lambda01, lambda11) {
    .Call('_mhazard_calcF', PACKAGE = 'mhazard', lambda10, lambda01, lambda11)
}

calc_lambda11 <- function(T1, T2, Y1, Y2, X, dij11, beta11) {
    .Call('_mhazard_calc_lambda11', PACKAGE = 'mhazard', T1, T2, Y1, Y2, X, dij11, beta11)
}

calcEE11 <- function(beta11, Y1, Y2, T1, T2, Delta1, Delta2, X, dij11) {
    .Call('_mhazard_calcEE11', PACKAGE = 'mhazard', beta11, Y1, Y2, T1, T2, Delta1, Delta2, X, dij11)
}

calc_drij <- function(Y1, Y2, T1, T2, Delta1, Delta2) {
    .Call('_mhazard_calc_drij', PACKAGE = 'mhazard', Y1, Y2, T1, T2, Delta1, Delta2)
}

margHaz <- function(Y, T, Delta) {
    .Call('_mhazard_margHaz', PACKAGE = 'mhazard', Y, T, Delta)
}

jointHazLambda <- function(Y1, Y2, T1, T2, Delta1, Delta2, method) {
    .Call('_mhazard_jointHazLambda', PACKAGE = 'mhazard', Y1, Y2, T1, T2, Delta1, Delta2, method)
}

calcTemp2 <- function(Fhat, Lambda10, Lambda01, Lambda11) {
    .Call('_mhazard_calcTemp2', PACKAGE = 'mhazard', Fhat, Lambda10, Lambda01, Lambda11)
}

jointHaz <- function(Y1, Y2, T1, T2, Delta1, Delta2) {
    .Call('_mhazard_jointHaz', PACKAGE = 'mhazard', Y1, Y2, T1, T2, Delta1, Delta2)
}

triHaz <- function(Y1, Y2, Y3, T1, T2, T3, Delta1, Delta2, Delta3) {
    .Call('_mhazard_triHaz', PACKAGE = 'mhazard', Y1, Y2, Y3, T1, T2, T3, Delta1, Delta2, Delta3)
}

calcTemp3 <- function(Fhat) {
    .Call('_mhazard_calcTemp3', PACKAGE = 'mhazard', Fhat)
}

getBootCI <- function(T) {
    .Call('_mhazard_getBootCI', PACKAGE = 'mhazard', T)
}

